### ISSUE TITLE
[SF-FEATURE-38] .err* is incomplete

### ISSUE THREAD

**Issue by milabs** [JWasm/JWasm#184]
**SF-FEATURE-38** | [.err\* is incomplete](http://www.sourceforge.net/p/jwasm/feature-requests/38) _created on_ `2012-09-17` _by_ `nobody`

---

<div class="markdown_content"><p>.386<br>
.model flat,stdcall<br>
option casemap:none<br>
.errndef Unicode,Say sth...<br>
.code<br>
start:<br>
ret<br>
end start</p>
<p>Test.asm(4) : Error A2209: Syntax error: Say</p>
<p><a href="http://msdn.microsoft.com/en-US/library/1sab7t6k%5C" rel="nofollow">http://msdn.microsoft.com/en-US/library/1sab7t6k\</a>(v=vs.110).aspx</p>
<p>Althought it works "pretty well" but I'd like to see "Error A2114: forced error" but not A2209: there is nothing to do with syntax.</p>
<p>When I use "ifdef Unicode" to control jwasm I have to face a lot of "Error A2102: Symbol not defined" and don't know how to fix it.</p></div>

**Comment by sergstetsuk** [comment]
try
.errndef Unicode,<"Say sth...">

**Comment by milabs** [comment]
@sergstetsuk The issue was imported from the sourceforge. If you have an idea of how to fix the code, welcome. We accepting pull requests :)

**Comment by sergstetsuk** [comment]
Sorry. I fixed my comment. If one'd like to see forced error then no text is needed in the end of .errndef

**Comment by milabs** [comment]
But anyway, is the `.errndef Unicode,Say sth...` syntax correct for the MASM and not correct for the JWasm?

**Comment by milabs** [comment]
Looks good to me except the amount of commits. Could you perform something like `rebase -i && fixup` and produce 1 commit? And forget about the test as that feature is not implemented in vanilla MASM. Thanks.

**Comment by sergstetsuk** [comment]
Check it out. Just one commit.

**Comment by milabs** [comment]
Merged with modifications as 9f257e0b33fb2e23a051b0527c1ea0cd3a2d31b1. Thank you.
