### ISSUE TITLE
Comment new Synwrite lexer "JWASM"

### ISSUE THREAD

**Issue by Alexey-T** [JWasm/JWasm#199]
Text editor SynWrite / CudaText-- have lexer "Assembly JWAsm". Install it via AddonManager.
Maybe someone can comment lexer? 
I hilited with red: `.names` (e.g. `.code`, `.if`)
I hilited with greenish: `label:`
I fold blocks `.if / .endif`
I put to "tree" procs, labels

**Comment by Alexey-T** [comment]
![cud](https://cloud.githubusercontent.com/assets/4154978/13722930/70e56ec8-e866-11e5-98df-8299fa1f5e30.png)

**Comment by milabs** [comment]
@Alexey-T So, what's the question?
